name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    name: Prettier Check
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Run Prettier
        run: npx prettier --check .

  build:
    runs-on: ubuntu-latest
    needs: prettier
    name: Build Next.js App
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js App
        run: yarn build
# You can add more jobs for other checks like tests, linting, etc.
